Repository python-trio/trio, pull requests merged in 2023-09, with the labels that each got.

#2780 Add py.typed in MANIFEST.in
  MANIFEST.in
Labels: typing

#2781 Fix KI protection decorator
  trio/_core/_ki.py
  trio/_tests/verify_types_darwin.json
  trio/_tests/verify_types_linux.json
  trio/_tests/verify_types_windows.json
Labels: typing

#2771 Add typing for some of the tests
  pyproject.toml
  trio/_core/_tests/test_asyncgen.py
  trio/_core/_tests/test_tutil.py
  trio/_core/_tests/test_windows.py
  trio/_core/_tests/tutil.py
  trio/_tests/check_type_completeness.py
  trio/_tests/pytest_plugin.py
  trio/_tests/test_abc.py
  trio/_tests/test_channel.py
  trio/_tests/test_deprecate.py
  trio/_tests/test_dtls.py
Labels: typing

#2794 Add types to `_signals`, `test_signals`
  pyproject.toml
  trio/_signals.py
  trio/_tests/test_signals.py
Labels: typing

#2784 make imports in tests on libraries not in install_requires skip on ImportError
  .github/workflows/ci.yml
  ci.sh
  trio/_tests/pytest_plugin.py
  trio/_tests/test_dtls.py
  trio/_tests/test_exports.py
  trio/_tests/test_ssl.py
  trio/_tests/tools/test_gen_exports.py
  trio/_tools/gen_exports.py
Labels: project meta

#2799 Add comment and assertion to `pidfd_open` workaround
  trio/_subprocess.py
Labels: polish

#2793 #2683: Make `_util.Final` support static analysis by converting to a decorator.
  trio/_channel.py
  trio/_core/_entry_queue.py
  trio/_core/_exceptions.py
  trio/_core/_local.py
  trio/_core/_mock_clock.py
  trio/_core/_parking_lot.py
  trio/_core/_run.py
  trio/_core/_unbounded_queue.py
  trio/_dtls.py
  trio/_highlevel_generic.py
  trio/_highlevel_socket.py
  trio/_path.py
  trio/_ssl.py
  trio/_subprocess.py
  trio/_sync.py
  trio/_tests/test_exports.py
  trio/_tests/test_util.py
  trio/_tests/verify_types_darwin.json
  trio/_tests/verify_types_linux.json
  trio/_tests/verify_types_windows.json
  trio/_unix_pipes.py
  trio/_util.py
  trio/_windows_pipes.py
  trio/testing/_fake_net.py
  trio/testing/_memory_streams.py
  trio/testing/_sequencer.py
Labels: typing

#2761 add types to io_windows
  pyproject.toml
  test-requirements.in
  test-requirements.txt
  trio/_core/_generated_io_windows.py
  trio/_core/_io_common.py
  trio/_core/_io_windows.py
  trio/_core/_tests/test_windows.py
  trio/_core/_windows_cffi.py
  trio/_subprocess_platform/waitid.py
  trio/_tests/verify_types_windows.json
  trio/_tools/gen_exports.py
  trio/_wait_for_object.py
Labels: typing

#2774 Typing SocketType, test_socket, test_highlevel_[socket, open_tcp_stream, open_tcp_listeners]
  .coveragerc
  docs/source/conf.py
  docs/source/reference-io.rst
  pyproject.toml
  trio/_abc.py
  trio/_core/_generated_io_epoll.py
  trio/_core/_generated_io_kqueue.py
  trio/_core/_io_epoll.py
  trio/_core/_io_kqueue.py
  trio/_dtls.py
  trio/_highlevel_open_tcp_listeners.py
  trio/_highlevel_open_tcp_stream.py
  trio/_highlevel_socket.py
  trio/_socket.py
  trio/_tests/test_highlevel_open_tcp_listeners.py
  trio/_tests/test_highlevel_open_tcp_stream.py
  trio/_tests/test_highlevel_socket.py
  trio/_tests/test_socket.py
  trio/_tests/verify_types_darwin.json
  trio/_tests/verify_types_linux.json
  trio/_tests/verify_types_windows.json
  trio/_tools/gen_exports.py
  trio/socket.py
  trio/testing/_fake_net.py
Labels: typing
