Repository python-trio/trio, pull requests merged in 2024-11, with the labels that each got.

#3121 Enable mypy's `disallow_any_explicit` flag.
  newsfragments/3121.misc.rst
  pyproject.toml
  src/trio/_core/_concat_tb.py
  src/trio/_core/_entry_queue.py
  src/trio/_core/_instrumentation.py
  src/trio/_core/_io_windows.py
  src/trio/_core/_ki.py
  src/trio/_core/_run.py
  src/trio/_core/_tests/test_guest_mode.py
  src/trio/_core/_tests/test_ki.py
  src/trio/_core/_tests/test_parking_lot.py
  src/trio/_core/_tests/test_run.py
  src/trio/_core/_thread_cache.py
  src/trio/_core/_traps.py
  src/trio/_dtls.py
  src/trio/_file_io.py
  src/trio/_highlevel_open_tcp_stream.py
  src/trio/_highlevel_serve_listeners.py
  src/trio/_path.py
  src/trio/_socket.py
  src/trio/_ssl.py
  src/trio/_tests/test_deprecate_strict_exception_groups_false.py
  src/trio/_tests/test_exports.py
  src/trio/_tests/test_highlevel_open_tcp_listeners.py
  src/trio/_tests/test_highlevel_open_tcp_stream.py
  src/trio/_tests/test_highlevel_serve_listeners.py
  src/trio/_tests/test_highlevel_ssl_helpers.py
  src/trio/_tests/test_socket.py
  src/trio/_tests/test_ssl.py
  src/trio/_tests/test_subprocess.py
  src/trio/_tests/test_testing_raisesgroup.py
  src/trio/_tests/test_threads.py
  src/trio/_tests/test_util.py
  src/trio/_threads.py
  src/trio/_util.py
  src/trio/testing/_fake_net.py
  test-requirements.in
  test-requirements.txt
Labels: dependencies

#3098 Enable flake8 annotations
  pyproject.toml
  src/trio/_channel.py
  src/trio/_core/_instrumentation.py
  src/trio/_core/_mock_clock.py
  src/trio/_core/_run.py
  src/trio/_dtls.py
  src/trio/_file_io.py
  src/trio/_highlevel_socket.py
  src/trio/_repl.py
  src/trio/_socket.py
  src/trio/_subprocess_platform/__init__.py
  src/trio/_sync.py
  src/trio/_tests/test_highlevel_open_tcp_listeners.py
  src/trio/_tests/test_highlevel_ssl_helpers.py
  src/trio/_tests/test_socket.py
  src/trio/_tests/test_ssl.py
  src/trio/_tests/test_subprocess.py
  src/trio/_tests/test_unix_pipes.py
  src/trio/_tests/test_util.py
  src/trio/testing/_check_streams.py
  src/trio/testing/_fake_net.py
  src/trio/testing/_memory_streams.py
  src/trio/testing/_raises_group.py
Labels: skip newsfragment

#3126 Get rid of `signal_raise`
  src/trio/_core/_tests/test_guest_mode.py
  src/trio/_core/_tests/test_ki.py
  src/trio/_signals.py
  src/trio/_tests/test_repl.py
  src/trio/_tests/test_signals.py
  src/trio/_tests/test_util.py
  src/trio/_util.py
Labels: skip newsfragment

#3143 Bump Ruff to 0.8.0
  .pre-commit-config.yaml
  pyproject.toml
  src/trio/_dtls.py
  src/trio/_socket.py
  src/trio/_subprocess_platform/__init__.py
  src/trio/_tests/test_testing_raisesgroup.py
  src/trio/_tests/test_threads.py
  src/trio/testing/_raises_group.py
  test-requirements.in
  test-requirements.txt
Labels: skip newsfragment

#3141 Type `RaisesGroup` properly
  docs/source/conf.py
  newsfragments/3141.bugfix.rst
  src/trio/_tests/test_testing_raisesgroup.py
  src/trio/_tests/type_tests/path.py
  src/trio/_tests/type_tests/raisesgroup.py
  src/trio/testing/_raises_group.py
Labels: typing
