Repository python-trio/trio, pull requests merged in 2024-01, with the labels that each got.

#2911 Cython Workaround
  src/trio/_core/_run.py
Labels: low-level

#2916 Suppress socket imports that might not exist on some systems
  src/trio/socket.py
Labels: user happiness

#2932 Enable `flake8-future-annotations`
  pyproject.toml
  src/trio/_subprocess_platform/__init__.py
  src/trio/_tests/test_file_io.py
  src/trio/socket.py
Labels: typing

#2935 change all instances of 'import typing as ...' to 'from typing import ...'
  src/trio/_tests/type_tests/check_wraps.py
  src/trio/_util.py
  src/trio/lowlevel.py
  src/trio/socket.py
Labels: typing
