Repository python-trio/trio, pull requests merged in 2024-12, with the labels that each got.

#3151 Get rid of using `__` for positional only arguments
  newsfragments/3094.misc.rst
  src/trio/_socket.py
Labels: typing

#3158 💄 Refactor the coveragepy config
  .codecov.yml
  .github/workflows/ci.yml
  pyproject.toml
  tests/cython/run_test_cython.py
  tests/cython/test_cython.pyx
Labels: project meta, skip newsfragment

#2541 Test sdist contents instead of Git checkout in CI
  .github/workflows/ci.yml
  MANIFEST.in
Labels: project meta, skip newsfragment

#3144 Disable ruff's COM812
  pyproject.toml
  src/trio/_core/_generated_io_kqueue.py
  src/trio/_core/_generated_io_windows.py
  src/trio/_core/_generated_run.py
Labels: skip newsfragment
